routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('customer.home.index');
})->name('homee');

Auth::routes();

Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
Route::post('/login/admin', 'Auth\LoginController@loginAdmin');
Route::post('/login', 'Auth\LoginController@login')->name('loginValidation');



Route::namespace('admin')->middleware('auth:web')->group( function () {
    Route::group(['prefix' => 'admin','as' => 'admin.'], function(){
        Route::get('/', 'homeController@index')->name('home');
    });

    Route::group(['prefix' => 'users','as' => 'users.'], function(){
        Route::get('/userProfile', 'usersController@index')->name('userProfile');
        Route::post('/userProfile/update/{profiles}', 'usersController@update')->name('updateProfile');

        //user account
        Route::get('/userAccount', 'usersController@indexUserAccount')->name('account');
        Route::get('/userAccount/create', 'usersController@addUserAccount')->name('addAccount');
        Route::post('/userAccount/store', 'usersController@storeUserAccount')->name('storeAccount');

        Route::get('/userAccount/edit/{id}', 'usersController@editUserAccount')->name('editAccount');
        Route::post('/userAccount/update/{id}', 'usersController@updateUserAccount')->name('updateAccount');
        Route::delete('/userAccount/delete/{userid}', 'usersController@destroyUserAccount')->name('destroyAccount');
    });

    Route::group(['prefix' => 'wisata','as' => 'wisata.'], function(){
        Route::get('/', 'wisataController@index')->name('index');
        Route::get('/create', 'wisataController@create')->name('create');
        Route::post('/store', 'wisataController@store')->name('store');
        Route::get('/edit/{id}', 'wisataController@edit')->name('edit');
        Route::post('/update/{id}', 'wisataController@update')->name('update');
        Route::delete('/delete/{id}', 'wisataController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'hotel','as' => 'hotel.'], function(){
        Route::get('/', 'hotelController@index')->name('index');
        Route::get('/create', 'hotelController@create')->name('create');
        Route::post('/store', 'hotelController@store')->name('store');
        Route::get('/edit/{id}', 'hotelController@edit')->name('edit');
        Route::post('/update/{id}', 'hotelController@update')->name('update');
        Route::delete('/delete/{id}', 'hotelController@destroy')->name('destroy');

        // kamar hotel
        Route::get('/kamar', 'hotelController@indexKamar')->name('indexKamar');
        Route::get('/kamar/edit/{id}', 'hotelController@editKamar')->name('editKamar');
        Route::get('/kamar/create/{id}', 'hotelController@createKamar')->name('createKamar');
        Route::post('/kamar/store', 'hotelController@storeKamar')->name('storeKamar');
        Route::post('/kamar/update/{id}', 'hotelController@updateKamar')->name('updateKamar');
        Route::delete('/kamar/delete/{id}', 'hotelController@destroyKamar')->name('destroyKamar');
    });

    Route::group(['prefix' => 'kuliner','as' => 'kuliner.'], function(){
        Route::get('/', 'kulinerController@index')->name('index');
        Route::get('/create', 'kulinerController@create')->name('create');
        Route::post('/store', 'kulinerController@store')->name('store');
        Route::get('/edit/{id}', 'kulinerController@edit')->name('edit');
        Route::post('/update/{id}', 'kulinerController@update')->name('update');
        Route::delete('/delete/{id}', 'kulinerController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'perhitungan','as' => 'perhitungan.'], function(){
        // kriteria
        Route::get('/kriteria', 'perhitunganController@indexKriteria')->name('indexKriteria');
        Route::get('/kriteria/create', 'perhitunganController@createKriteria')->name('createKriteria');
        Route::post('/kriteria/store', 'perhitunganController@storeKriteria')->name('storeKriteria');
        Route::get('/kriteria/edit/{id}', 'perhitunganController@editKriteria')->name('editKriteria');
        Route::post('/kriteria/update/{id}', 'perhitunganController@updateKriteria')->name('updateKriteria');
        Route::delete('/kriteria/delete/{id}', 'perhitunganController@destroyKriteria')->name('destroyKriteria');

        // range
        Route::get('/range', 'perhitunganController@indexRange')->name('indexRange');
        Route::get('/range/create', 'perhitunganController@createRange')->name('createRange');
        Route::post('/range/store', 'perhitunganController@storeRange')->name('storeRange');
        Route::get('/range/edit/{id}', 'perhitunganController@editRange')->name('editRange');
        Route::post('range/update/{id}', 'perhitunganController@updateRange')->name('updateRange');
        Route::delete('/range/delete/{id}', 'perhitunganController@destroyRange')->name('destroyRange');

        // Lokasi Awal
        Route::get('/lokasi', 'perhitunganController@indexLokasi')->name('indexLokasi');
        Route::get('/lokasi/create', 'perhitunganController@createLokasi')->name('createLokasi');
        Route::post('/lokasi/store', 'perhitunganController@storeLokasi')->name('storeLokasi');
        Route::get('/lokasi/edit/{id}', 'perhitunganController@editLokasi')->name('editLokasi');
        Route::post('/lokasi/update/{id}', 'perhitunganController@updateLokasi')->name('updateLokasi');
        Route::delete('/lokasi/delete/{id}', 'perhitunganController@destroyLokasi')->name('destroyLokasi');

        // data prediksi
        Route::get('/dataPrediksi', 'perhitunganController@indexDataPrediksi')->name('indexDataPrediksi');
        Route::get('/dataPrediksi/create', 'perhitunganController@createDataPrediksi')->name('createDataPrediksi');
        Route::get('/getData', 'perhitunganController@getDataPrediksi')->name('getDataPrediksi');
        Route::post('/dataPrediksi/store', 'perhitunganController@storeDataPrediksi')->name('storeDataPrediksi');
        Route::get('/dataPrediksi/edit/{id}', 'perhitunganController@editDataPrediksi')->name('editDataPrediksi');
        Route::post('/dataPrediksi/update/{id}', 'perhitunganController@updateDataPrediksi')->name('updateDataPrediksi');
        Route::delete('/dataPrediksi/delete/{id}', 'perhitunganController@destroyDataPrediksi')->name('destroyDataPrediksi');
        

    });

    Route::group(['prefix' => 'touring','as' => 'touring.'], function(){
        Route::get('/', 'touringController@index')->name('index');
        Route::get('/detailWisata/{id}', 'touringController@detailWisata')->name('detailWisata');
        Route::get('/detailHotel/{id}', 'touringController@detailHotel')->name('detailHotel');
        Route::get('/detailKuliner/{id}', 'touringController@detailKuliner')->name('detailKuliner');
        Route::get('/formTour', 'touringController@formTour')->name('formTour');
        Route::get('/startRoute', 'touringController@dostartroute')->name('dostartroute');
        Route::get('/startTouring', 'touringController@startTouring')->name('startTouring');
        // Route::get('/edit/{id}', 'kulinerController@edit')->name('edit');
        // Route::post('/update/{id}', 'kulinerController@update')->name('update');
        // Route::delete('/delete/{id}', 'kulinerController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'pesanan', 'as' => 'pesanan.'], function(){
        Route::get('/', 'pesananController@index')->name('index');

    });

});


Route::namespace('customer')->group( function () {
    Route::group(['prefix' => 'home','as' => 'home.'], function(){
        Route::get('/', 'homeController@index')->name('index');
    });

    Route::group(['prefix' => 'trip', 'as' => 'trip.'], function(){
        Route::get('/', 'tripController@index')->name('index');
        Route::get('/detailWisata/{id}', 'tripController@detailWisata')->name('detailWisata');
        Route::get('/detailKuliner/{id}', 'tripController@detailKuliner')->name('detailKuliner');
        Route::get('/detailHotel/{id}', 'tripController@detailHotel')->name('detailHotel');
        Route::get('/formTour', 'tripController@formTour')->name('formTour');
        Route::get('/startRoute', 'tripController@dostartroute')->name('dostartroute');
        Route::get('/startTouring', 'tripController@startTouring')->name('startTouring');
    });

    Route::group(['prefix' => 'service', 'as' => 'service.'], function(){
        Route::get('/', 'serviceController@index')->name('index');
    });

    Route::group(['prefix' => 'cart', 'as' => 'cart.'], function(){
        Route::get('/', 'cartController@index')->name('index');
        Route::post('/addCart', 'cartController@create')->name('create');
        Route::post('/updateCart/{id}', 'cartController@update')->name('update');
        Route::delete('/delete/{cartid}', 'cartController@destroy')->name('destroy');
    });
       

    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function(){
        Route::get('/', 'profileController@index')->name('index');
        Route::get('/getRegency', 'profileController@getRegency')->name('getRegency');
        Route::post('/update/{id}', 'profileController@update')->name('update');
    });

    

});

app/Models/Range.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Range extends Model{
    protected $fillable = [
        'idKriteria','nama', 'rentang', 'bobot',
    ];

    public function kriteria(){
        return $this->belongsTo('App\Models\Kriteria', 'idKriteria','id');
    }
}

app/Http/Controllers/admin/perhitunganController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\perhitunganRepository;
use App\Http\Requests\KriteriaStoreRequest;
use App\Http\Requests\KriteriaUpdateRequest;
use App\Http\Requests\RangeStoreRequest;
use App\Http\Requests\RangeUpdateRequest;
use App\Http\Requests\LokasiStoreRequest;
use App\Http\Requests\LokasiUpdateRequest;
use App\Http\Requests\DataPrediksiStoreRequest;
use App\Http\Requests\DataPrediksiUpdateRequest;
use App\Models\Kriteria;
use App\Models\Range;
use App\Models\Lokasi;
use App\Models\Wisata;
use App\Models\Hotel;
use App\Models\Kuliner;
use App\Models\KategoriData;
use App\Models\DataPrediksi;
use Illuminate\Support\Facades\DB;
use Redirect;

class perhitunganController extends Controller{
    
    private $perhitunganRepository;

    public function __construct(perhitunganRepository $perhitunganRepository){
        $this->perhitunganRepository = $perhitunganRepository;
    }
    
    // kriteria
    public function indexKriteria(){
        $kriteria = $this->perhitunganRepository->getKriteria();
        return view('admin.perhitungan.kriteria.index', compact('kriteria'));
    }

    public function createKriteria(){
        return view('admin.perhitungan.kriteria.create');
    }

    public function storeKriteria(KriteriaStoreRequest $request){
        $this->perhitunganRepository->storeKriteria($request);
        return redirect(route('perhitungan.indexKriteria'))->with('status', 'Data Kriteria Berhasil Ditambahkan');
    }

    public function editKriteria($id){
        $edit = $this->perhitunganRepository->getKriteria(null, $id);
        return view('admin.perhitungan.kriteria.edit', compact('edit'));
    }

    public function updateKriteria(KriteriaUpdateRequest $request, Kriteria $kriteria, $id){
        $this->perhitunganRepository->updateKriteria($request, $kriteria, $id);
        return redirect(route('perhitungan.indexKriteria'))->with('status', 'Data Kriteria Berhasil Dirubah');
    }

    public function destroyKriteria($id){
        $kriteria = Kriteria::where('id', $id)->first();
        $range = Range::where('idKriteria', '=', $id)->get();
        if($range->count() > 0){
            return Redirect::back()->with('danger', 'Data Range Tidak Kosong, Harap Hapus Terlebih Dahulu');
        }elseif($range->count() == 0){
            $kriteria->forceDelete();
            return redirect(route('perhitungan.indexKriteria'))->with('status', 'Data Kriteria Berhasil Dihapus');
        }
    }

    // range
    public function indexRange(){
        $range = $this->perhitunganRepository->getRange();
        return view('admin.perhitungan.range.index', compact('range'));
    }

    public function createRange(){
        $kriteria = $this->perhitunganRepository->createRange();
        return view('admin.perhitungan.range.create', compact('kriteria'));
    }

    public function storeRange(RangeStoreRequest $request){
        $this->perhitunganRepository->storeRange($request);
        return redirect(route('perhitungan.indexRange'))->with('status', 'Data Range Berhasil Ditambahkan');
    }

    public function editRange($id){
        $edit = Range::find($id);
        $kriteria = Kriteria::all();
        return view('admin.perhitungan.range.edit', compact('edit', 'kriteria'));
    }

    public function updateRange(RangeUpdateRequest $request, Range $range, $id){
        $this->perhitunganRepository->updateRange($request, $range, $id);
        return redirect(route('perhitungan.indexRange'))->with('status', 'Data Range Berhasil Dirubah');
    }

    public function destroyRange($id){
        $this->perhitunganRepository->destroyRange($id);
        return redirect(route('perhitungan.indexRange'))->with('status', 'Data Range Berhasil Di Hapus');
    }

    // lokasi awal
    public function indexLokasi(){
        $lokasi = $this->perhitunganRepository->getLokasi();
        return view('admin.perhitungan.lokasiAwal.index', compact('lokasi'));
    }

    public function createLokasi(){
        return view('admin.perhitungan.lokasiAwal.create');
    }

    public function storeLokasi(LokasiStoreRequest $request){
        $this->perhitunganRepository->storeLokasi($request);
        return redirect(route('perhitungan.indexLokasi'))->with('status', 'Data Lokasi Berhasil Ditambahkan');
    }

    public function editLokasi($id){
        $edit = $this->perhitunganRepository->getLokasi(null, $id);
        return view('admin.perhitungan.lokasiAwal.edit', compact('edit'));
    }

    public function updateLokasi(LokasiUpdateRequest $request, Lokasi $lokasi, $id){
        $this->perhitunganRepository->updateLokasi($request, $lokasi, $id);
        return redirect(route('perhitungan.indexLokasi'))->with('status', 'Data Lokasi Berhasil Dirubah');
    }

    public function destroyLokasi($id){
        $lokasi = Lokasi::where('id', $id)->first();
        $prediksi = DataPrediksi::where('idLokasi', '=', $id)->get();
        if($prediksi->count() > 0){
            return Redirect::back()->with('danger', 'Data Prediksi Tidak Kosong, Harap Hapus Terlebih Dahulu');
        }elseif($prediksi->count() == 0){
            $lokasi->forceDelete();
            return redirect(route('perhitungan.indexLokasi'))->with('status', 'Data Lokasi Berhasil Dihapus');
        }
    }

    // data prediksi
    public function indexDataPrediksi(){
        $dataPrediksi = $this->perhitunganRepository->getDataPrediksi();
        return view('admin.perhitungan.dataPrediksi.index', compact('dataPrediksi'));
    }

    public function createDataPrediksi(){
        $lokasi = Lokasi::all();
        $kategoriData = KategoriData::all();

        return view('admin.perhitungan.dataPrediksi.create', compact('lokasi', 'kategoriData'));
    }

    public function getDataPrediksi(Request $request){
        $rangeJarak = Range::where('idKriteria', 1)->get();
        $jarak = $request->get('jarak');
        $idKategoriData = $request->get('idKategoriData');

        if($idKategoriData == 1){
            $wisata = Wisata::all();
            return json_encode($wisata);
        }elseif($idKategoriData == 2){
            $hotel = Hotel::all();
            return json_encode($hotel);
        }elseif($idKategoriData==3){
            $kuliner = Kuliner::all();
            return json_encode($kuliner);
        }


        // for($i=0;$i<count($rangeJarak);$i++){
        //     if($jarak <= $rangeJarak[$i]->rentang){
        //         $idRangeJarak = $rangeJarak[$i];
            
        //         $variabel += $idRangeJarak;
        //         return json_encode($idRangeJarak);
        //     }
        // }
    }

    public function storeDataPrediksi(DataPrediksiStoreRequest $request){
        $this->perhitunganRepository->storeDataPrediksi($request);
        return redirect(route('perhitungan.indexDataPrediksi'))->with('status', 'Data Prediksi Berhasil Ditambahkan');
    }

    public function editDataPrediksi($id){
        $edit = DataPrediksi::find($id);
        $lokasi = Lokasi::all();
        $kategoriData = KategoriData::all();
        return view('admin.perhitungan.dataPrediksi.edit', compact('edit', 'lokasi', 'kategoriData'));
    }

    public function updateDataPrediksi(DataPrediksiUpdateRequest $request, DataPrediksi $dataPrediksi, $id){
        $this->perhitunganRepository->updateDataPrediksi($request, $dataPrediksi, $id);
        return redirect(route('perhitungan.indexDataPrediksi'))->with('status', 'Data Prediksi Berhasil Dirubah');
    }

    public function destroyDataPrediksi($id){
        $this->perhitunganRepository->destroyDataPrediksi($id);
        return redirect(route('perhitungan.indexDataPrediksi'))->with('status', 'Data Prediksi Berhasil Dihapus');
    }
}

resources/views/admin/perhitungan/range/create.blade.php
@extends('admin.layouts.app')
@section('content')
@section('perhitungan','active')
@section('range', 'active')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Add Range</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('perhitungan.indexRange') }}">Range</a></li>
                            <li class="breadcrumb-item active">Add Range</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-primary">
                            <div class="card-header">
                            </div>
                            <form role="form" action="{{ route('perhitungan.storeRange') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="card-body">
                                    <div class="form-group">
                                        <label>Kriteria</label>
                                        <select class="custom-select" name="idKriteria">
                                            <option>Pilih Kriteria</option>
                                            @foreach($kriteria as $kriterias)
                                                <option value="{{ $kriterias->id }}">{{ $kriterias->nama }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="name">Nama Range</label>
                                        <input type="text" class="form-control" id="name" placeholder="Masukkan Nama Range" name="nama">
                                    </div>
                                    <div class="form-group">
                                        <label for="name">Rentang (Masukkan Rentangan Terjauh ex:20-30 maka ditulis 30)</label>
                                        <input type="number" class="form-control" id="name" placeholder="Masukkan Rentangan" name="rentang">
                                    </div>
                                    <div class="form-group">
                                        <label for="name">Bobot Rentang (Masukkan Bobot Rentang sesuai dengan tingkat kepentingan dan tidak boleh dari 1 ex: 0.2</label>
                                        <input type="number" step="0.01" min="0" max="10" class="form-control" id="name" placeholder="Masukkan Bobot" name="bobot">
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary float-right">Simpan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
@section('extrascript')
    <script>
        $(function () {
            $('.textarea').summernote()
        })
    </script>
@endsection

resources/views/admin/perhitungan/range/edit.blade.php
@extends('admin.layouts.app')
@section('content')
@section('perhitungan','active')
@section('range', 'active')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Add Range</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('perhitungan.indexRange') }}">Range</a></li>
                            <li class="breadcrumb-item active">Add Range</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-primary">
                            <div class="card-header">
                            </div>
                            <form role="form" action="{{ route('perhitungan.updateRange', $edit->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="card-body">
                                    <div class="form-group">
                                        <label>Kriteria</label>
                                        <select class="custom-select" name="idKriteria">
                                            <option>Pilih Kriteria</option>
                                            @foreach($kriteria as $kriterias)
                                                <option {{$edit->idKriteria == $kriterias->id  ? 'selected' : ''}} value="{{ $kriterias->id }}">{{ $kriterias->nama }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="name">Nama Range</label>
                                        <input type="text" class="form-control" id="name" placeholder="Masukkan Nama Range" name="nama" value="{{ $edit->nama }}">
                                    </div>
                                    <div class="form-group">
                                        <label for="name">Rentang (Sertakan Dengan Satuan Jika Ada)</label>
                                        <input type="number" class="form-control" id="name" placeholder="Masukkan Rentangan" name="rentang" value="{{ $edit->rentang }}">
                                    </div>
                                    <div class="form-group">
                                        <label for="name">Bobot</label>
                                        <input type="text" class="form-control" id="name" placeholder="Masukkan Bobot" name="bobot" value="{{ $edit->bobot }}">
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary float-right">Simpan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
@section('extrascript')
    <script>
        $(function () {
            $('.textarea').summernote()
        })
    </script>
@endsection

resources/views/admin/perhitungan/range/index.blade.php
@extends('admin.layouts.app')
@section('extrahead')
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
@endsection

@section('content')
@section('perhitungan', 'active')
@section('range', 'active')
<div class="content-wrapper">
		<section class="content-header">
			<div class="container-fluid">
				<div class="row mb-2">
					<div class="col-sm-6">
						<h1>Range</h1>
					</div>
					<div class="col-sm-6">
						<ol class="breadcrumb float-sm-right">
							<li class="breadcrumb-item active">Range</li>
						</ol>
					</div>
				</div>
			</div>
		</section>
		<section class="content">
			<div class="row">
				<div class="col-12">
					@if (session('status'))
						<div class="col-md-12">
							<div class="card bg-gradient-success">
								<div class="card-header">
									<h3 class="card-title">Success</h3>
									<div class="card-tools">
										<button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
										</button>
									</div>
								</div>
								<div class="card-body">
									{{ session('status')}}
								</div>
							</div>
						</div>
					@endif
					<div class="card">
						<div class="card-header">
							<a href="{{ route('perhitungan.createRange') }}" type="button" class="btn btn-info float-right"><i class="fas fa-plus"></i>Add Range</a>
						</div>
						<div class="card-body">
							<table id="example1" class="table table-bordered table-striped">
								<thead>
									<tr>
										<th>No</th>
										<th>Range</th>
										<th>Kriteria</th>
										<th>Rentang</th>
                                        <th>Bobot</th>
										<th>Action</th>	
									</tr>
								</thead>
								<tbody>
									@foreach($range as $ranges)
										<tr>
											<td>{{ $loop->iteration }}</td>
											<td>{{ $ranges->nama }}</td>
											<td>{{ $ranges->kriteria()->first()->nama }}</td>
											<td>{{ $ranges->rentang }}</td>
                                            <td>{{ $ranges->bobot }}</td>
											<td>
												<a href="{{ route('perhitungan.editRange', $ranges->id) }}"><i class="fa fa-edit"></i></a>||
												<a href="" onclick="event.preventDefault(); if(confirm('Apakah Anda yakin?', 'Konfirmasi Penghapusan Pengguna')){ $('form#hapus{{ $loop->iteration }}').submit(); }"><i class="fa fa-trash"></i></a>
												<form id="hapus{{ $loop->iteration }}" action="{{ route('perhitungan.destroyRange', $ranges->id) }}" method="POST">
													@csrf
													@method('DELETE')
												</form>
											</td>
										</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
@endsection

@section('extrascript')
    <script src="{{ asset('assets/plugins/datatables/jquery.dataTables.js') }}"></script>
	<script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
    <script>
		$(function () {
			$("#example1").DataTable();
			$('#example2').DataTable({
			"paging": true,
			"lengthChange": false,
			"searching": false,
			"ordering": true,
			"info": true,
			"autoWidth": false,
			});
		});
    </script>
@endsection