routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('customer.home.index');
})->name('homee');

Auth::routes();

Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
Route::post('/login/admin', 'Auth\LoginController@loginAdmin');
Route::post('/login', 'Auth\LoginController@login')->name('loginValidation');



Route::namespace('admin')->middleware('auth:web')->group( function () {
    Route::group(['prefix' => 'admin','as' => 'admin.'], function(){
        Route::get('/', 'homeController@index')->name('home');
    });

    Route::group(['prefix' => 'users','as' => 'users.'], function(){
        Route::get('/userProfile', 'usersController@index')->name('userProfile');
        Route::post('/userProfile/update/{profiles}', 'usersController@update')->name('updateProfile');

        //user account
        Route::get('/userAccount', 'usersController@indexUserAccount')->name('account');
        Route::get('/userAccount/create', 'usersController@addUserAccount')->name('addAccount');
        Route::post('/userAccount/store', 'usersController@storeUserAccount')->name('storeAccount');

        Route::get('/userAccount/edit/{id}', 'usersController@editUserAccount')->name('editAccount');
        Route::post('/userAccount/update/{id}', 'usersController@updateUserAccount')->name('updateAccount');
        Route::delete('/userAccount/delete/{userid}', 'usersController@destroyUserAccount')->name('destroyAccount');
    });

    Route::group(['prefix' => 'wisata','as' => 'wisata.'], function(){
        Route::get('/', 'wisataController@index')->name('index');
        Route::get('/create', 'wisataController@create')->name('create');
        Route::post('/store', 'wisataController@store')->name('store');
        Route::get('/edit/{id}', 'wisataController@edit')->name('edit');
        Route::post('/update/{id}', 'wisataController@update')->name('update');
        Route::delete('/delete/{id}', 'wisataController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'hotel','as' => 'hotel.'], function(){
        Route::get('/', 'hotelController@index')->name('index');
        Route::get('/create', 'hotelController@create')->name('create');
        Route::post('/store', 'hotelController@store')->name('store');
        Route::get('/edit/{id}', 'hotelController@edit')->name('edit');
        Route::post('/update/{id}', 'hotelController@update')->name('update');
        Route::delete('/delete/{id}', 'hotelController@destroy')->name('destroy');

        // kamar hotel
        Route::get('/kamar', 'hotelController@indexKamar')->name('indexKamar');
        Route::get('/kamar/edit/{id}', 'hotelController@editKamar')->name('editKamar');
        Route::get('/kamar/create/{id}', 'hotelController@createKamar')->name('createKamar');
        Route::post('/kamar/store', 'hotelController@storeKamar')->name('storeKamar');
        Route::post('/kamar/update/{id}', 'hotelController@updateKamar')->name('updateKamar');
        Route::delete('/kamar/delete/{id}', 'hotelController@destroyKamar')->name('destroyKamar');
    });

    Route::group(['prefix' => 'kuliner','as' => 'kuliner.'], function(){
        Route::get('/', 'kulinerController@index')->name('index');
        Route::get('/create', 'kulinerController@create')->name('create');
        Route::post('/store', 'kulinerController@store')->name('store');
        Route::get('/edit/{id}', 'kulinerController@edit')->name('edit');
        Route::post('/update/{id}', 'kulinerController@update')->name('update');
        Route::delete('/delete/{id}', 'kulinerController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'perhitungan','as' => 'perhitungan.'], function(){
        // kriteria
        Route::get('/kriteria', 'perhitunganController@indexKriteria')->name('indexKriteria');
        Route::get('/kriteria/create', 'perhitunganController@createKriteria')->name('createKriteria');
        Route::post('/kriteria/store', 'perhitunganController@storeKriteria')->name('storeKriteria');
        Route::get('/kriteria/edit/{id}', 'perhitunganController@editKriteria')->name('editKriteria');
        Route::post('/kriteria/update/{id}', 'perhitunganController@updateKriteria')->name('updateKriteria');
        Route::delete('/kriteria/delete/{id}', 'perhitunganController@destroyKriteria')->name('destroyKriteria');

        // range
        Route::get('/range', 'perhitunganController@indexRange')->name('indexRange');
        Route::get('/range/create', 'perhitunganController@createRange')->name('createRange');
        Route::post('/range/store', 'perhitunganController@storeRange')->name('storeRange');
        Route::get('/range/edit/{id}', 'perhitunganController@editRange')->name('editRange');
        Route::post('range/update/{id}', 'perhitunganController@updateRange')->name('updateRange');
        Route::delete('/range/delete/{id}', 'perhitunganController@destroyRange')->name('destroyRange');

        // Lokasi Awal
        Route::get('/lokasi', 'perhitunganController@indexLokasi')->name('indexLokasi');
        Route::get('/lokasi/create', 'perhitunganController@createLokasi')->name('createLokasi');
        Route::post('/lokasi/store', 'perhitunganController@storeLokasi')->name('storeLokasi');
        Route::get('/lokasi/edit/{id}', 'perhitunganController@editLokasi')->name('editLokasi');
        Route::post('/lokasi/update/{id}', 'perhitunganController@updateLokasi')->name('updateLokasi');
        Route::delete('/lokasi/delete/{id}', 'perhitunganController@destroyLokasi')->name('destroyLokasi');

        // data prediksi
        Route::get('/dataPrediksi', 'perhitunganController@indexDataPrediksi')->name('indexDataPrediksi');
        Route::get('/dataPrediksi/create', 'perhitunganController@createDataPrediksi')->name('createDataPrediksi');
        Route::get('/getData', 'perhitunganController@getDataPrediksi')->name('getDataPrediksi');
        Route::post('/dataPrediksi/store', 'perhitunganController@storeDataPrediksi')->name('storeDataPrediksi');
        Route::get('/dataPrediksi/edit/{id}', 'perhitunganController@editDataPrediksi')->name('editDataPrediksi');
        Route::post('/dataPrediksi/update/{id}', 'perhitunganController@updateDataPrediksi')->name('updateDataPrediksi');
        Route::delete('/dataPrediksi/delete/{id}', 'perhitunganController@destroyDataPrediksi')->name('destroyDataPrediksi');
        

    });

    Route::group(['prefix' => 'touring','as' => 'touring.'], function(){
        Route::get('/', 'touringController@index')->name('index');
        Route::get('/detailWisata/{id}', 'touringController@detailWisata')->name('detailWisata');
        Route::get('/detailHotel/{id}', 'touringController@detailHotel')->name('detailHotel');
        Route::get('/detailKuliner/{id}', 'touringController@detailKuliner')->name('detailKuliner');
        Route::get('/formTour', 'touringController@formTour')->name('formTour');
        Route::get('/startRoute', 'touringController@dostartroute')->name('dostartroute');
        Route::get('/startTouring', 'touringController@startTouring')->name('startTouring');
        // Route::get('/edit/{id}', 'kulinerController@edit')->name('edit');
        // Route::post('/update/{id}', 'kulinerController@update')->name('update');
        // Route::delete('/delete/{id}', 'kulinerController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'pesanan', 'as' => 'pesanan.'], function(){
        Route::get('/', 'pesananController@index')->name('index');

    });

});


Route::namespace('customer')->group( function () {
    Route::group(['prefix' => 'home','as' => 'home.'], function(){
        Route::get('/', 'homeController@index')->name('index');
    });

    Route::group(['prefix' => 'trip', 'as' => 'trip.'], function(){
        Route::get('/', 'tripController@index')->name('index');
        Route::get('/detailWisata/{id}', 'tripController@detailWisata')->name('detailWisata');
        Route::get('/detailKuliner/{id}', 'tripController@detailKuliner')->name('detailKuliner');
        Route::get('/detailHotel/{id}', 'tripController@detailHotel')->name('detailHotel');
        Route::get('/formTour', 'tripController@formTour')->name('formTour');
        Route::get('/startRoute', 'tripController@dostartroute')->name('dostartroute');
        Route::get('/startTouring', 'tripController@startTouring')->name('startTouring');
    });

    Route::group(['prefix' => 'service', 'as' => 'service.'], function(){
        Route::get('/', 'serviceController@index')->name('index');
    });

    Route::group(['prefix' => 'cart', 'as' => 'cart.'], function(){
        Route::get('/', 'cartController@index')->name('index');
        Route::post('/addCart', 'cartController@create')->name('create');
        Route::post('/updateCart/{id}', 'cartController@update')->name('update');
        Route::delete('/delete/{cartid}', 'cartController@destroy')->name('destroy');
    });
       

    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function(){
        Route::get('/', 'profileController@index')->name('index');
        Route::get('/getRegency', 'profileController@getRegency')->name('getRegency');
        Route::post('/update/{id}', 'profileController@update')->name('update');
    });

    

});

resources/views/admin/touring/detailWisata.blade.php
@extends('admin.layouts.app')
@section('content')
@section('touring', 'active')
	<div class="content-wrapper">
		<section class="content-header">
			<div class="container-fluid">
				<div class="row mb-2">
					<div class="col-sm-6">
						<h1>{{ $detail->nama }}</h1>
					</div>
					<div class="col-sm-6">
						<ol class="breadcrumb float-sm-right">
							<li class="breadcrumb-item"><a href="{{ route('touring.index') }}">Touring</a></li>
							<li class="breadcrumb-item active">Detail Wisata</li>
						</ol>
					</div>
				</div>
			</div>
		</section>
		<section class="content">
			<div class="card card-solid">
				<div class="card-body">
					<div class="row">
						<div class="col-12 col-sm-6">
							<div class="col-12">
								<img src="{{asset('assets/img/wisata/'.$detail->foto)}}" class="product-image" alt="Product Image">
							</div>
						</div>
						<div class="col-12 col-sm-6">
							<h3 class="my-3">{{ $detail->nama }}</h3>
							<p>{{ $detail->alamat }}</p>
							<hr>
							<div class="bg-gray py-2 px-3 mt-4">
								<h2 class="mb-0">
									Rp. {{ $detail->harga }}
								</h2>
							</div><br>
							<a href="{{ route('wisata.create') }}" type="button" class="btn btn-info"><i class="fas fa-shopping-cart"></i> Add Cart</a>
						</div>
					</div>
					<div class="row mt-4">
						<nav class="w-100">
							<div class="nav nav-tabs" id="product-tab" role="tablist">
								<a class="nav-item nav-link active" id="product-desc-tab" data-toggle="tab" href="#product-desc" role="tab" aria-controls="product-desc" aria-selected="true">Description</a>
								<a class="nav-item nav-link" id="product-comments-tab" data-toggle="tab" href="#product-comments" role="tab" aria-controls="product-comments" aria-selected="false">Comments</a>
								<a class="nav-item nav-link" id="product-rating-tab" data-toggle="tab" href="#product-rating" role="tab" aria-controls="product-rating" aria-selected="false">Rating</a>
							</div>
						</nav>
						<div class="tab-content p-3" id="nav-tabContent">
							<div class="tab-pane fade show active" id="product-desc" role="tabpanel" aria-labelledby="product-desc-tab"><p>{{ $detail->deskripsi }}</p>
							<hr></div>
							<div class="tab-pane fade" id="product-comments" role="tabpanel" aria-labelledby="product-comments-tab"> Vivamus rhoncus nisl sed venenatis luctus. Sed condimentum risus ut tortor feugiat laoreet. Suspendisse potenti. Donec et finibus sem, ut commodo lectus. Cras eget neque dignissim, placerat orci interdum, venenatis odio. Nulla turpis elit, consequat eu eros ac, consectetur fringilla urna. Duis gravida ex pulvinar mauris ornare, eget porttitor enim vulputate. Mauris hendrerit, massa nec aliquam cursus, ex elit euismod lorem, vehicula rhoncus nisl dui sit amet eros. Nulla turpis lorem, dignissim a sapien eget, ultrices venenatis dolor. Curabitur vel turpis at magna elementum hendrerit vel id dui. Curabitur a ex ullamcorper, ornare velit vel, tincidunt ipsum. </div>
							<div class="tab-pane fade" id="product-rating" role="tabpanel" aria-labelledby="product-rating-tab"> Cras ut ipsum ornare, aliquam ipsum non, posuere elit. In hac habitasse platea dictumst. Aenean elementum leo augue, id fermentum risus efficitur vel. Nulla iaculis malesuada scelerisque. Praesent vel ipsum felis. Ut molestie, purus aliquam placerat sollicitudin, mi ligula euismod neque, non bibendum nibh neque et erat. Etiam dignissim aliquam ligula, aliquet feugiat nibh rhoncus ut. Aliquam efficitur lacinia lacinia. Morbi ac molestie lectus, vitae hendrerit nisl. Nullam metus odio, malesuada in vehicula at, consectetur nec justo. Quisque suscipit odio velit, at accumsan urna vestibulum a. Proin dictum, urna ut varius consectetur, sapien justo porta lectus, at mollis nisi orci et nulla. Donec pellentesque tortor vel nisl commodo ullamcorper. Donec varius massa at semper posuere. Integer finibus orci vitae vehicula placerat. </div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
@endsection

resources/views/admin/touring/index.blade.php
@extends('admin.layouts.app')
@section('content')
@section('touring', 'active')
	<div class="content-wrapper">
		<section class="content-header">
			<div class="container-fluid">
				<div class="row mb-2">
					<div class="col-sm-6">
						<h1>Touring</h1>
					</div>
					<div class="col-sm-6">
						<ol class="breadcrumb float-sm-right">
							<li class="breadcrumb-item active">Touring</li>
						</ol>
					</div>
				</div>
			</div>
		</section>
		<section class="content">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<a href="{{ route('touring.formTour') }}" type="button" class="btn btn-info float-right">Start Tour</a>
							<div id="myModal" class="modal fade" role="dialog">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<h4 class="modal-title">Start Touring</h4>
											<button type="button" class="close" data-dismiss="modal">&times;</button>
										</div>
									</div>
								</div>
							</div>
							<div class="card-header p-2">
								<ul class="nav nav-pills">
									<li class="nav-item"><a class="nav-link active" href="#wisata" data-toggle="tab">Wisata</a></li>
									<li class="nav-item"><a class="nav-link" href="#hotel" data-toggle="tab">Hotel</a></li>
									<li class="nav-item"><a class="nav-link" href="#kuliner" data-toggle="tab">Kuliner</a></li>
								</ul>
							</div>
							<div class="card-body">
								<div class="tab-content">
									<div class="active tab-pane" id="wisata">
										<div class="card card-solid">
											<div class="card-body pb-0">
												<div class="row d-flex align-items-stretch">
												@foreach($wisata as $wisatas)
													<div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
														<div class="card bg-light">
															<div class="card-header text-muted border-bottom-0">
																@for ($i = 1; $i <= $wisatas->rating; $i++)
																	<span class="fa fa-star checked"></span>
																@endfor
															</div>
															<div class="card-body pt-0">
																<div class="row">
																	<div class="col-7">
																		<h2 class="lead"><b>{{ $wisatas->nama }}</b></h2>
																		<p class="text-muted text-sm"><b>Deskripsi: </b> {{ $wisatas->deskripsi }} </p>
																		<ul class="ml-4 mb-0 fa-ul text-muted">
																			<li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Alamat: {{ $wisatas->alamat }}</li>
																		</ul>
																	</div>
																		<div class="col-5 text-center">
																		<img src="{{asset('assets/img/wisata/'.$wisatas->foto)}}" alt="" class="img-thumbnail">
																	</div>
																</div>
															</div>
															<div class="card-footer">
																<div class="text-right">
																	<a href="{{ route('touring.detailWisata', $wisatas->id) }}" class="btn btn-sm btn-primary">
																		<i class="fas fa-eye"></i> View Detail
																	</a>
																</div>
															</div>
														</div>
													</div>
												@endforeach
												{{ $wisata->links() }}
												</div>
											</div>
										</div>
									</div>
									<div class="tab-pane" id="hotel">
										<div class="card card-solid">
											<div class="card-body pb-0">
												<div class="row d-flex align-items-stretch">
												@foreach($hotel as $hotels)
													<div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
														<div class="card bg-light">
															<div class="card-header text-muted border-bottom-0">
																@for ($i = 1; $i <= $hotels->rating; $i++)
																	<span class="fa fa-star checked"></span>
																@endfor
															</div>
															<div class="card-body pt-0">
																<div class="row">
																	<div class="col-7">
																		<h2 class="lead"><b>{{ $hotels->nama }}</b></h2>
																		<p class="text-muted text-sm"><b>Deskripsi: </b> {{ $hotels->deskripsi }} </p>
																		<ul class="ml-4 mb-0 fa-ul text-muted">
																			<li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Alamat: {{ $hotels->alamat }}</li>
																		</ul>
																	</div>
																		<div class="col-5 text-center">
																		<img src="{{asset('assets/img/hotel/'.$hotels->foto)}}" alt="" class="img-thumbnail">
																	</div>
																</div>
															</div>
															<div class="card-footer">
																<div class="text-right">
																	<a href="{{ route('touring.detailHotel', $hotels->id) }}" class="btn btn-sm btn-primary">
																		<i class="fas fa-eye"></i> View Detail
																	</a>
																</div>
															</div>
														</div>
													</div>
												@endforeach
												{{ $hotel->links() }}
												</div>
											</div>
										</div>
									</div>
									<div class="tab-pane" id="kuliner">
										<div class="card card-solid">
											<div class="card-body pb-0">
												<div class="row d-flex align-items-stretch">
												@foreach($kuliner as $kuliners)
													<div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
														<div class="card bg-light">
															<div class="card-header text-muted border-bottom-0">
																@for ($i = 1; $i <= $kuliners->rating; $i++)
																	<span class="fa fa-star checked"></span>
																@endfor
															</div>
															<div class="card-body pt-0">
																<div class="row">
																	<div class="col-7">
																		<h2 class="lead"><b>{{ $kuliners->nama }}</b></h2>
																		<p class="text-muted text-sm"><b>Deskripsi: </b> {{ $kuliners->deskripsi }} </p>
																		<ul class="ml-4 mb-0 fa-ul text-muted">
																			<li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Alamat: {{ $kuliners->alamat }}</li>
																		</ul>
																	</div>
																		<div class="col-5 text-center">
																		<img src="{{asset('assets/img/kuliner/'.$kuliners->foto)}}" alt="" class="img-thumbnail">
																	</div>
																</div>
															</div>
															<div class="card-footer">
																<div class="text-right">
																	<a href="{{ route('touring.detailKuliner', $kuliners->id) }}" class="btn btn-sm btn-primary">
																		<i class="fas fa-eye"></i> View Detail
																	</a>
																</div>
															</div>
														</div>
													</div>
												@endforeach
												{{ $kuliner->links() }}
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
@endsection

resources/views/admin/touring/startTour.blade.php
@extends('admin.layouts.app')
@section('content')
@section('touring', 'active')
	<div class="content-wrapper">
		<section class="content-header">
			<div class="container-fluid">
				<div class="row mb-2">
					<div class="col-sm-6">
						<h1>Touring</h1>
					</div>
					<div class="col-sm-6">
						<ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('touring.index') }}">Touring</a></li>
							<li class="breadcrumb-item active">Start Touring</li>
						</ol>
					</div>
				</div>
			</div>
		</section>
		<section class="content">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<a href="{{ route('touring.formTour') }}" type="button" class="btn btn-info float-right">Start Tour</a>
							<div class="card-header p-2">
								<ul class="nav nav-pills">
									<li class="nav-item"><a class="nav-link active" href="#wisata" data-toggle="tab">Wisata</a></li>
									<li class="nav-item"><a class="nav-link" href="#hotel" data-toggle="tab">Hotel</a></li>
									<li class="nav-item"><a class="nav-link" href="#kuliner" data-toggle="tab">Kuliner</a></li>
								</ul>
							</div>
							<div class="card-body">
								<div class="tab-content">
									<div class="active tab-pane" id="wisata">
										<div class="card card-solid">
											<div class="card-body pb-0">
												<div class="row d-flex align-items-stretch">
												@if($items[0] != null)
												@foreach($items[0] as $wisatas)
													<div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
														<div class="card bg-light">
															<div class="card-header text-muted border-bottom-0">
																bintang
															</div>
															<div class="card-body pt-0">
																<div class="row">
																	<div class="col-7">
																		<h2 class="lead"><b>({{ $loop->iteration }}) {{ $wisatas->first()->nama }}</b></h2>
																		<p class="text-muted text-sm"><b>About: </b> {{ $wisatas->first()->deskripsi }} </p>
																		<ul class="ml-4 mb-0 fa-ul text-muted">
																			<li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Alamat: {{ $wisatas->first()->alamat }}</li>
																		</ul>
																	</div>
																		<div class="col-5 text-center">
																		<img src="{{asset('assets/img/wisata/'.$wisatas->first()->foto)}}" alt="" class="img-thumbnail">
																	</div>
																</div>
															</div>
															<div class="card-footer">
																<div class="text-right">
																	<a href="{{ route('touring.detailWisata', $wisatas->first()->id) }}" class="btn btn-sm btn-primary">
																		<i class="fas fa-eye"></i> View Detail
																	</a>
																</div>
															</div>
														</div>
													</div>
												@endforeach
												@endif
												</div>
											</div>
										</div>
									</div>
									<div class="active tab-pane" id="hotel">
										<div class="card card-solid">
											<div class="card-body pb-0">
												<div class="row d-flex align-items-stretch">
												@if($items[1] != null)
													@foreach($items[1] as $hotels)
														<div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
															<div class="card bg-light">
																<div class="card-header text-muted border-bottom-0">
																	bintang
																</div>
																<div class="card-body pt-0">
																	<div class="row">
																		<div class="col-7">
																			<h2 class="lead"><b>({{ $loop->iteration }}) {{ $hotels->first()->nama }}</b></h2>
																			<p class="text-muted text-sm"><b>About: </b> {{ $hotels->first()->deskripsi }} </p>
																			<ul class="ml-4 mb-0 fa-ul text-muted">
																				<li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Alamat: {{ $hotels->first()->alamat }}</li>
																			</ul>
																		</div>
																			<div class="col-5 text-center">
																			<img src="{{asset('assets/img/hotel/'.$hotels->first()->foto)}}" alt="" class="img-thumbnail">
																		</div>
																	</div>
																</div>
																<div class="card-footer">
																	<div class="text-right">
																		<a href="{{ route('touring.detailHotel', $hotels->first()->id) }}" class="btn btn-sm btn-primary">
																			<i class="fas fa-eye"></i> View Detail
																		</a>
																	</div>
																</div>
															</div>
														</div>
													@endforeach
												@endif
												</div>
											</div>
										</div>
									</div>
									<div class="active tab-pane" id="kuliner">
										<div class="card card-solid">
											<div class="card-body pb-0">
												<div class="row d-flex align-items-stretch">
												@if($items[2] != null)
												@foreach($items[2] as $kuliners)
													<div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
														<div class="card bg-light">
															<div class="card-header text-muted border-bottom-0">
																bintang
															</div>
															<div class="card-body pt-0">
																<div class="row">
																	<div class="col-7">
																		<h2 class="lead"><b>({{ $loop->iteration }}) {{ $kuliners->first()->nama }}</b></h2>
																		<p class="text-muted text-sm"><b>About: </b> {{ $kuliners->first()->deskripsi }} </p>
																		<ul class="ml-4 mb-0 fa-ul text-muted">
																			<li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Alamat: {{ $kuliners->first()->alamat }}</li>
																		</ul>
																	</div>
																		<div class="col-5 text-center">
																		<img src="{{asset('assets/img/kuliner/'.$kuliners->first()->foto)}}" alt="" class="img-thumbnail">
																	</div>
																</div>
															</div>
															<div class="card-footer">
																<div class="text-right">
																	<a href="{{ route('touring.detailKuliner', $kuliners->first()->id) }}" class="btn btn-sm btn-primary">
																		<i class="fas fa-eye"></i> View Detail
																	</a>
																</div>
															</div>
														</div>
													</div>
												@endforeach
												@endif
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
@endsection